### ISSUE TITLE
monorepo化

### ISSUE THREAD

**Issue by neila** [unchain-tech/Polygon-Generative-NFT#5]
- [x] https://github.com/unchain-tech/generative-nft-library をこちらのレポジトリに取り込む
- [x] 呼び出しとからへんをいい感じにする
- [x] 学習コンテンツを修正する

**Comment by honganji** [comment]
monorepo化完了しました。フロント、コントラクト、NFT画像を作成するプロジェクトをトップディレクトリから操作できます。
